version: '3.3'

services:
  # Servicio de PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carshop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
# Servicio de redis
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  # Servicio de tu app NestJS
  api:
    build: .
    container_name: nest_app
    command: npm run start:dev
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: carshop
    ports:
      - "3000:3000"

volumes:
  db_data:
